name: SSH to GCP VM via GitHub Actions 

on:
  push:
    branches: [ "main" ]

jobs:
  access-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        GCP_VM_EXTERNAL_IP: ${{ secrets.GCP_VM_EXTERNAL_IP }}
        GCP_USERNAME: ${{ secrets.GCP_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/key
        sudo chmod 600 ~/.ssh/key
        ssh-keyscan -H "$GCP_VM_EXTERNAL_IP" > ~/.ssh/known_hosts
    - name: Echo SSH 
      run: |
        pwd
        ls -al
        ls -al ~/.ssh
    - name: Connect to GCP VM and Run Command
      run: |
        ssh -i ~/.ssh/key $GCP_USERNAME@$GCP_VM_EXTERNAL_IP
